name: Cloud Deployment

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install doctl
        run: |
          sudo snap install doctl
          sudo snap connect doctl:kube-config
          sudo snap connect doctl:ssh-keys
          sudo snap connect doctl:dot-docker
          doctl version

      - name: Authenticate with DigitalOcean
        run: |
          mkdir -p ~/.config
          doctl auth init --context default --access-token ${{ secrets.CLOUD_API_TOKEN }}

      - name: Create Container Registry (if it does not exist)
        run: |
          doctl registry get game-recommender || doctl registry create game-recommender --region ams3


      - name: DigitalOcean Container Registry Login
        run: doctl registry login

      - name: Build & Push Docker Image
        run: |
          docker build -t registry.digitalocean.com/game-recommender/gameapi:latest .
          docker push registry.digitalocean.com/game-recommender/gameapi:latest
